config/routes.rb
Rails.application.routes.draw do
  devise_for :users

#resources :dds
#resources :dds do
#post :about_us
#get :about_us, only: :index
#end

  #get "/about_us", to: "dds#about_us", as: :about_us

  DdsController.action_methods.each do |action|
    get "/#{action}", to: "dds##{action}", as: "#{action}"
  end

root 'dds#home'

resources :ontechnologies
resources :careers
resources :pictures
resources :products


match '/contactforms',     to: 'contactforms#new',             via: 'get'
resources "contactforms", only: [:new, :create]
end

app/models/career.rb
class Career < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :career_img, :styles => { :medium => "500x300#", :small => "350x250>" }, :default_url => "missing.jpg"
	validates_attachment_content_type :career_img, :content_type => /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
 
end

app/models/ontechnology.rb
class Ontechnology < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :ontechnology_img, :styles => { :medium => "500x300#", :small => "350x250>" }, :default_url => "missing.jpg"
	validates_attachment_content_type :ontechnology_img, :content_type => /\Aimage\/.*\Z/
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :image, :styles => { :medium => "500x300#", :small => "350x250>" }, :default_url => "missing.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user

	

	has_attached_file :product_img, :styles => { :medium => "500x300#", :small => "350x250>" }, :default_url => "missing.jpg"
	validates_attachment_content_type :product_img, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :products
	has_many :careers
	has_many :pictures
	has_many :ontechnologies

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
before_action :find_career, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
before_action :authenticate_user!, except: [:index, :show]

def index
	
		@careers = Career.all.order("created_at DESC")
end

def show
	#@comments = Comment.where(career_id: @career)
	#@random_career = career.where.not(id: @career).order("RANDOM()").first
end

def new
	@career = current_user.careers.build
end

def create
	@career = current_user.careers.build(career_params)

	if @career.save
		redirect_to @career
	else
		render 'new'
	end
end

def edit
end

def update
	if @career.update(career_params)
		redirect_to @career
	else
		render 'edit'
	end
end

def destroy
	@career.destroy
	redirect_to root_path
end

def upvote
	@career.upvote_by current_user
	redirect_to :back
end

def downvote
	@career.downvote_by current_user
	redirect_to :back
end

private

def find_career
	@career = Career.find(params[:id])
end

def career_params
	params.require(:career).permit(:advertiser, :title, :description, :qualification, :contract_nature, :salary, :start_date, :application_deadline, :career_img)
end
end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
	
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/dds_controller.rb
class DdsController < ApplicationController
    def home
    end

    def about_us
    	render
    end

    def csr
    	render
    end

    def business_continuity_management  
    	render
    end

    def cloud_computing
    	render
    end

    def project_management 
    	render
    end

    def partnerships
    	render
    end
end

app/controllers/ontechnologies_controller.rb
class OntechnologiesController < ApplicationController

before_action :find_ontechnology, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
before_action :authenticate_user!, except: [:index, :show]

def index
	
		@ontechnologies = Ontechnology.all.order("created_at DESC")
end

def show
	#@comments = Comment.where(ontechnology_id: @ontechnology)
	#@random_ontechnology = ontechnology.where.not(id: @ontechnology).order("RANDOM()").first
end

def new
	@ontechnology = current_user.ontechnologies.build
end

def create
	@ontechnology = current_user.ontechnologies.build(ontechnology_params)

	if @ontechnology.save
		redirect_to @ontechnology
	else
		render 'new'
	end
end

def edit
end

def update
	if @ontechnology.update(ontechnology_params)
		redirect_to @ontechnology
	else
		render 'edit'
	end
end

def destroy
	@ontechnology.destroy
	redirect_to root_path
end

def upvote
	@ontechnology.upvote_by current_user
	redirect_to :back
end

def downvote
	@ontechnology.downvote_by current_user
	redirect_to :back
end

private

def find_ontechnology
	@ontechnology = Ontechnology.find(params[:id])
end

def ontechnology_params
	params.require(:ontechnology).permit(:title, :body, :ontechnology_img, :url)
end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :find_picture, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
before_action :authenticate_user!, except: [:index, :show]

def index
	
		@pictures = Picture.all.order("created_at DESC")
end

def show
	#@comments = Comment.where(picture_id: @picture)
	#@random_picture = picture.where.not(id: @picture).order("RANDOM()").first
end

def new
	@picture = current_user.pictures.build
end

def create
	@picture = current_user.pictures.build(picture_params)

	if @picture.save
		redirect_to @picture
	else
		render 'new'
	end
end

def edit
end

def update
	if @picture.update(picture_params)
		redirect_to @picture
	else
		render 'edit'
	end
end

def destroy
	@picture.destroy
	redirect_to root_path
end

def upvote
	@picture.upvote_by current_user
	redirect_to :back
end

def downvote
	@picture.downvote_by current_user
	redirect_to :back
end

private

def find_picture
	@picture = Picture.find(params[:id])
end

def picture_params
	params.require(:picture).permit(:advertiser, :title, :description, :qualification, :contract_nature, :salary, :start_date, :application_deadline, :picture_img)
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :find_product, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
before_action :authenticate_user!, except: [:index, :show]

def index
	
		@products = Product.all.order("created_at DESC")
end

def show
	#@comments = Comment.where(product_id: @product)
	#@random_product = product.where.not(id: @product).order("RANDOM()").first
end

def new
	@product = current_user.products.build
end

def create
	@product = current_user.products.build(product_params)

	if @product.save
		redirect_to @product
	else
		render 'new'
	end
end

def edit
end

def update
	if @product.update(product_params)
		redirect_to @product
	else
		render 'edit'
	end
end

def destroy
	@product.destroy
	redirect_to root_path
end

def upvote
	@product.upvote_by current_user
	redirect_to :back
end

def downvote
	@product.downvote_by current_user
	redirect_to :back
end

private

def find_product
	@product = Product.find(params[:id])
end

def product_params
	params.require(:product).permit(:title, :description, :url, :product_img)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dds_helper.rb
module DdsHelper
end

app/helpers/ontechnologies_helper.rb
module OntechnologiesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/careers/_form.html.haml
= simple_form_for @career do |f|
	= f.input :advertiser
	= f.input :title
	= f.input :description
	= f.input :qualification
	= f.input :contract_nature
	= f.input :salary
	= f.input :start_date
	= f.input :application_deadline

	= f.button :submit

app/views/careers/edit.html.haml
%h1 Edit on tech job


= render 'form'

app/views/careers/index.html.haml
.divfold50
	- @careers.each do |career|
		.divfold50
			.col-md-3
				%p
				Department:
				%br
				= career.advertiser
				%p
				Apply before:
				%br
				= career.application_deadline
			.col-md-9
				%h3= link_to career.title, career
				= career.description
				%br
				= link_to "read details", career
		%hr
					


				

app/views/careers/new.html.haml
%h1 Add new job advert

= render 'form'

app/views/careers/show.html.haml
.divfold57 
	.divfold50
			
		%p
			- if @career.user == current_user
				= link_to "Edit", edit_career_path(@career)
				= link_to "Destroy", career_path(@career), method: :delete, data: { confirm: "career will be deleted" }



		%h1= @career.title 
		Description:
		.divfold56
			%p= @career.description
		qualification:
		.divfold56
			%p= @career.qualification
		contract_nature:
		.divfold56
			%p= @career.contract_nature
		salary:
		.divfold56
			%p= @career.salary
		start_date:
		.divfold56
			%p= @career.start_date
		application_deadline:
		.divfold56
			%p= @career.application_deadline

app/views/careers/show2.html.haml
#product_show
	%h1= @product.title
	%p.username
	= @product.user.user_name
	=time_ago_in_words(@product.created_at)

	.clearfix
		.product_image_description
		 	= image_tag @product.product_img.url(:medium)
			.description= simple_format(@product.description)
		.product_data
			= link_to "Visit Link", @product.link, class: "button"
			= link_to like_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-up
				= pluralize(@product.get_upvotes.size, "like")
			= link_to dislike_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-down
				= pluralize(@product.get_downvotes.size, "Like")



%h1= @product.title 
%p= @product.url
%p= @product.description
%p= @product.from_price
%p= @product.to_price
%p= @product.user.user_name

%p
	= @product.get_upvotes.size
	Likes

%p
	= @product.get_downvotes.size
	Dislikes


= link_to "Like", like_product_path(@product), method: :get
= link_to "Dislike", dislike_product_path(@product), method: :get
	%i.fa.fa-thumbs-o-down

#comment
	%h2.comment_count= pluralize(@product.comments.count, "Comment")
	- @comments.each do |comment|
		.comment
			%p.username= comment.user.user_name
			%p.content= comment.content

	= render 'comments/form'

= link_to "Home", root_path 
= link_to "Edit", edit_product_path(@product)
= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "Product will be deleted" }
= link_to 'Log Out', destroy_user_session_path, method: :delete

app/views/careers/show3.html.haml
.col-md-7
	.fireplace2show

		#product_show
			%h1= @product.title
			%p.username
			= @product.user.user_name
			=time_ago_in_words(@product.created_at)

			.clearfix
				.product_image_description
					= image_tag @product.product_img.url
					.description= simple_format(@product.description)
				.product_data
					= link_to "Visit Link", @product.url, class: "button"
					= link_to like_product_path(@product), method: :get, class: "data" do
						%i.fa.fa-thumbs-o-up
						= pluralize(@product.get_upvotes.size, "like")
					= link_to dislike_product_path(@product), method: :get, class: "data" do
						%i.fa.fa-thumbs-o-down
						= pluralize(@product.get_downvotes.size, "Disike")
					%p.data
						%i.fa.fa-comments-o
						=pluralize(@product.comments.count, "Comment")
					- if @product.user == current_user
						= link_to "Edit", edit_product_path(@product)
						= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "Product will be deleted" }

		#comments
			%h2.comment_count= pluralize(@product.comments.count, "Comment")
			- @comments.each do |comment|
				.comment
					%p.username= comment.user.user_name
					%p.content= comment.content

			= render 'comments/form'

.col-md-3

	#random_product
		%h3 Random product
		.product
			.product_image
				= link_to (image_tag @random_product.product_img.url), product_path(@random_product)
			.product_content
				.title
					%h2= link_to @random_product.title, product_path(@random_product)
				.data.clearfix
					%p.username
					Product added by
					= @random_product.user.user_name
				%p.buttons
					%span
						%i.fa.fa-comments-o
						= @random_product.comments.count
					%span
						%i.fa.fa-thumbs-o-up
						= @random_product.get_likes.size

app/views/contacts/_form.html.haml
.divfold50
  %h1 Contact
  = simple_form_for @contact, :html => {:class => 'formfields' } do |f|
    = f.input :name, :required => true
    = f.input :email, :required => true
    = f.input :message, :as => :text, :required => false, :input_html => {:rows => 10}

    .hidden
      = f.input :nickname, :hint => 'Leave this field blank!'
    .form-actions
      = f.button :submit, 'Send message', :class=> "btn btn-primary"

app/views/contacts/create.html.haml
.divfold50
  %h1 Thank you for your message.
  %p We'll get back to you soon.

app/views/contacts/new.html.haml
= render 'contacts/form'

app/views/ontechnologies/_form.html.haml
= simple_form_for @ontechnology do |f|
	= f.input :title
	= f.input :body
	= f.input :url
	= f.input :ontechnology_img

	= f.button :submit

app/views/ontechnologies/edit.html.haml
%h1 Edit news

= render 'form'

app/views/ontechnologies/index.html.haml
.divfold50
	- @ontechnologies.each do |ontechnology|
		.divfold50
			.col-md-3
				.trybsindexnews
					= link_to (image_tag ontechnology.ontechnology_img.url(:small))
			.col-md-9
				%h3= link_to ontechnology.title, ontechnology
				= ontechnology.body.first(110) + " " + "....."
				%br
				= link_to "read details", ontechnology
		%hr

				

app/views/ontechnologies/new.html.haml
%h1 Add new 

= render 'form'

app/views/ontechnologies/show.html.haml
.divfold57 
	.divfold50
		%h1= @ontechnology.title
		%p.username
		= image_tag @ontechnology.ontechnology_img.url
		= simple_format(@ontechnology.body)
		%p= @ontechnology.url
			
		%br
			
		%p
			- if @ontechnology.user == current_user
				= link_to "Edit", edit_ontechnology_path(@ontechnology)
				= link_to "Destroy", ontechnology_path(@ontechnology), method: :delete, data: { confirm: "ontechnology will be deleted" }

app/views/ontechnologies/show2.html.haml
#product_show
	%h1= @product.title
	%p.username
	= @product.user.user_name
	=time_ago_in_words(@product.created_at)

	.clearfix
		.product_image_description
		 	= image_tag @product.product_img.url(:medium)
			.description= simple_format(@product.description)
		.product_data
			= link_to "Visit Link", @product.link, class: "button"
			= link_to like_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-up
				= pluralize(@product.get_upvotes.size, "like")
			= link_to dislike_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-down
				= pluralize(@product.get_downvotes.size, "Like")



%h1= @product.title 
%p= @product.url
%p= @product.description
%p= @product.from_price
%p= @product.to_price
%p= @product.user.user_name

%p
	= @product.get_upvotes.size
	Likes

%p
	= @product.get_downvotes.size
	Dislikes


= link_to "Like", like_product_path(@product), method: :get
= link_to "Dislike", dislike_product_path(@product), method: :get
	%i.fa.fa-thumbs-o-down

#comment
	%h2.comment_count= pluralize(@product.comments.count, "Comment")
	- @comments.each do |comment|
		.comment
			%p.username= comment.user.user_name
			%p.content= comment.content

	= render 'comments/form'

= link_to "Home", root_path 
= link_to "Edit", edit_product_path(@product)
= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "Product will be deleted" }
= link_to 'Log Out', destroy_user_session_path, method: :delete

app/views/ontechnologies/show3.html.haml
.col-md-7
	.fireplace2show

		#product_show
			%h1= @product.title
			%p.username
			= @product.user.user_name
			=time_ago_in_words(@product.created_at)

			.clearfix
				.product_image_description
					= image_tag @product.product_img.url
					.description= simple_format(@product.description)
				.product_data
					= link_to "Visit Link", @product.url, class: "button"
					= link_to like_product_path(@product), method: :get, class: "data" do
						%i.fa.fa-thumbs-o-up
						= pluralize(@product.get_upvotes.size, "like")
					= link_to dislike_product_path(@product), method: :get, class: "data" do
						%i.fa.fa-thumbs-o-down
						= pluralize(@product.get_downvotes.size, "Disike")
					%p.data
						%i.fa.fa-comments-o
						=pluralize(@product.comments.count, "Comment")
					- if @product.user == current_user
						= link_to "Edit", edit_product_path(@product)
						= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "Product will be deleted" }

		#comments
			%h2.comment_count= pluralize(@product.comments.count, "Comment")
			- @comments.each do |comment|
				.comment
					%p.username= comment.user.user_name
					%p.content= comment.content

			= render 'comments/form'

.col-md-3

	#random_product
		%h3 Random product
		.product
			.product_image
				= link_to (image_tag @random_product.product_img.url), product_path(@random_product)
			.product_content
				.title
					%h2= link_to @random_product.title, product_path(@random_product)
				.data.clearfix
					%p.username
					Product added by
					= @random_product.user.user_name
				%p.buttons
					%span
						%i.fa.fa-comments-o
						= @random_product.comments.count
					%span
						%i.fa.fa-thumbs-o-up
						= @random_product.get_likes.size

app/views/pictures/edit.html.haml
%h1 Edit picture


= render 'form'

app/views/pictures/new.html.haml
%h1 Add new picture

= render 'form'

app/views/pictures/show.html.haml
.divfold57 
	.divfold50
		%h1= @picture.title
		%p.username
		= image_tag @picture.picture_img.url
		= simple_format(@picture.description)
			
		%br
			
		%p
			- if @picture.user == current_user
				= link_to "Edit", edit_picture_path(@picture)
				= link_to "Destroy", picture_path(@picture), method: :delete, data: { confirm: "picture will be deleted" }



		%h1= @picture.title 
		Description:
		.divfold56
			%p= @picture.description
		qualification:
		.divfold56
			%p= @picture.qualification
		contract_nature:
		.divfold56
			%p= @picture.contract_nature
		salary:
		.divfold56
			%p= @picture.salary
		start_date:
		.divfold56
			%p= @picture.start_date
		application_deadline:
		.divfold56
			%p= @picture.application_deadline

app/views/pictures/show2.html.haml
#product_show
	%h1= @product.title
	%p.username
	= @product.user.user_name
	=time_ago_in_words(@product.created_at)

	.clearfix
		.product_image_description
		 	= image_tag @product.product_img.url(:medium)
			.description= simple_format(@product.description)
		.product_data
			= link_to "Visit Link", @product.link, class: "button"
			= link_to like_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-up
				= pluralize(@product.get_upvotes.size, "like")
			= link_to dislike_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-down
				= pluralize(@product.get_downvotes.size, "Like")



%h1= @product.title 
%p= @product.url
%p= @product.description
%p= @product.from_price
%p= @product.to_price
%p= @product.user.user_name

%p
	= @product.get_upvotes.size
	Likes

%p
	= @product.get_downvotes.size
	Dislikes


= link_to "Like", like_product_path(@product), method: :get
= link_to "Dislike", dislike_product_path(@product), method: :get
	%i.fa.fa-thumbs-o-down

#comment
	%h2.comment_count= pluralize(@product.comments.count, "Comment")
	- @comments.each do |comment|
		.comment
			%p.username= comment.user.user_name
			%p.content= comment.content

	= render 'comments/form'

= link_to "Home", root_path 
= link_to "Edit", edit_product_path(@product)
= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "Product will be deleted" }
= link_to 'Log Out', destroy_user_session_path, method: :delete

app/views/pictures/show3.html.haml
.col-md-7
	.fireplace2show

		#product_show
			%h1= @product.title
			%p.username
			= @product.user.user_name
			=time_ago_in_words(@product.created_at)

			.clearfix
				.product_image_description
					= image_tag @product.product_img.url
					.description= simple_format(@product.description)
				.product_data
					= link_to "Visit Link", @product.url, class: "button"
					= link_to like_product_path(@product), method: :get, class: "data" do
						%i.fa.fa-thumbs-o-up
						= pluralize(@product.get_upvotes.size, "like")
					= link_to dislike_product_path(@product), method: :get, class: "data" do
						%i.fa.fa-thumbs-o-down
						= pluralize(@product.get_downvotes.size, "Disike")
					%p.data
						%i.fa.fa-comments-o
						=pluralize(@product.comments.count, "Comment")
					- if @product.user == current_user
						= link_to "Edit", edit_product_path(@product)
						= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "Product will be deleted" }

		#comments
			%h2.comment_count= pluralize(@product.comments.count, "Comment")
			- @comments.each do |comment|
				.comment
					%p.username= comment.user.user_name
					%p.content= comment.content

			= render 'comments/form'

.col-md-3

	#random_product
		%h3 Random product
		.product
			.product_image
				= link_to (image_tag @random_product.product_img.url), product_path(@random_product)
			.product_content
				.title
					%h2= link_to @random_product.title, product_path(@random_product)
				.data.clearfix
					%p.username
					Product added by
					= @random_product.user.user_name
				%p.buttons
					%span
						%i.fa.fa-comments-o
						= @random_product.comments.count
					%span
						%i.fa.fa-thumbs-o-up
						= @random_product.get_likes.size

app/views/products/show.html.haml
.divfold57 
	.divfold50
		%h1= @product.title
		%p.username
		= image_tag @product.product_img.url
		= simple_format(@product.description)
			
		%br
			
		%p
			- if @product.user == current_user
				= link_to "Edit", edit_product_path(@product)
				= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "product will be deleted" }



		%h1= @product.title 
		Description:.divfold57 
	.col-md-7
		.fireplace2show
			%h1= @product.title
			%p.username
			= image_tag @product.product_img.url
			= simple_format(@product.description)
			= link_to "Visit Link", @product.url
			%br
			= link_to like_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-up
				= pluralize(@product.get_upvotes.size, "like")
			= link_to dislike_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-down
				= pluralize(@product.get_downvotes.size, "Disike")
			%p.data
				%i.fa.fa-comments-o
				
			%p
				- if @product.user == current_user
					= link_to "Edit", edit_product_path(@product)
					= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "Product will be deleted" }



			%h1= @product.title 
			Description:
			.divfold56
				%p= @product.description
			From prices:
			%p 
			.divfold56 
				ksh
				= @product.price
		
			%p	

			= pluralize(@product.comments.count, "Comment")
			%br
			- @comments.each do |comment|
				= comment.user.user_name
				|
				= comment.content
				|

			= render 'comments/form'
		

		


	.col-md-3
		.fireplace2showrandom
			%h3 You can also try this service wth us

			= link_to (image_tag @random_product.product_img.url), product_path(@random_product)
					
			%h2= link_to @random_product.title, product_path(@random_product)
			%span
				%i.fa.fa-comments-o
				= @random_product.comments.count
			%span
				%i.fa.fa-thumbs-o-up
				= @random_product.get_likes.size


.divfold57 	
	.col-md-7
		.divfold56
			= link_to "Contact us", new_contact_path
	.col-md-3
		.divfold56
			= link_to "See Our Staff", staffs_path
		.divfold56
			%p= @product.description
		qualification:
		.divfold56
			%p= @product.qualification
		contract_nature:
		.divfold56
			%p= @product.contract_nature
		salary:
		.divfold56
			%p= @product.salary
		start_date:
		.divfold56
			%p= @product.start_date
		application_deadline:
		.divfold56
			%p= @product.application_deadline

app/views/products/show2.html.haml
#product_show
	%h1= @product.title
	%p.username
	= @product.user.user_name
	=time_ago_in_words(@product.created_at)

	.clearfix
		.product_image_description
		 	= image_tag @product.product_img.url(:medium)
			.description= simple_format(@product.description)
		.product_data
			= link_to "Visit Link", @product.link, class: "button"
			= link_to like_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-up
				= pluralize(@product.get_upvotes.size, "like")
			= link_to dislike_product_path(@product), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-down
				= pluralize(@product.get_downvotes.size, "Like")



%h1= @product.title 
%p= @product.url
%p= @product.description
%p= @product.from_price
%p= @product.to_price
%p= @product.user.user_name

%p
	= @product.get_upvotes.size
	Likes

%p
	= @product.get_downvotes.size
	Dislikes


= link_to "Like", like_product_path(@product), method: :get
= link_to "Dislike", dislike_product_path(@product), method: :get
	%i.fa.fa-thumbs-o-down

#comment
	%h2.comment_count= pluralize(@product.comments.count, "Comment")
	- @comments.each do |comment|
		.comment
			%p.username= comment.user.user_name
			%p.content= comment.content

	= render 'comments/form'

= link_to "Home", root_path 
= link_to "Edit", edit_product_path(@product)
= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "Product will be deleted" }
= link_to 'Log Out', destroy_user_session_path, method: :delete

app/views/products/show3.html.haml
.col-md-7
	.fireplace2show

		#product_show
			%h1= @product.title
			%p.username
			= @product.user.user_name
			=time_ago_in_words(@product.created_at)

			.clearfix
				.product_image_description
					= image_tag @product.product_img.url
					.description= simple_format(@product.description)
				.product_data
					= link_to "Visit Link", @product.url, class: "button"
					= link_to like_product_path(@product), method: :get, class: "data" do
						%i.fa.fa-thumbs-o-up
						= pluralize(@product.get_upvotes.size, "like")
					= link_to dislike_product_path(@product), method: :get, class: "data" do
						%i.fa.fa-thumbs-o-down
						= pluralize(@product.get_downvotes.size, "Disike")
					%p.data
						%i.fa.fa-comments-o
						=pluralize(@product.comments.count, "Comment")
					- if @product.user == current_user
						= link_to "Edit", edit_product_path(@product)
						= link_to "Destroy", product_path(@product), method: :delete, data: { confirm: "Product will be deleted" }

		#comments
			%h2.comment_count= pluralize(@product.comments.count, "Comment")
			- @comments.each do |comment|
				.comment
					%p.username= comment.user.user_name
					%p.content= comment.content

			= render 'comments/form'

.col-md-3

	#random_product
		%h3 Random product
		.product
			.product_image
				= link_to (image_tag @random_product.product_img.url), product_path(@random_product)
			.product_content
				.title
					%h2= link_to @random_product.title, product_path(@random_product)
				.data.clearfix
					%p.username
					Product added by
					= @random_product.user.user_name
				%p.buttons
					%span
						%i.fa.fa-comments-o
						= @random_product.comments.count
					%span
						%i.fa.fa-thumbs-o-up
						= @random_product.get_likes.size