config/routes.rb
Rails.application.routes.draw do
  devise_for :users

#resources :dds
#resources :dds do
#post :about_us
#get :about_us, only: :index
#end

  #get "/about_us", to: "dds#about_us", as: :about_us

  DdsController.action_methods.each do |action|
    get "/#{action}", to: "dds##{action}", as: "#{action}"
  end

root 'dds#home'

resources :ontechnologies
resources :careers
resources :pictures
resources :products


match '/contactforms',     to: 'contactforms#new',             via: 'get'
resources "contactforms", only: [:new, :create]
end

app/models/career.rb
class Career < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :career_img, :styles => { :medium => "500x300#", :small => "350x250>" }, :default_url => "missing.jpg"
	validates_attachment_content_type :career_img, :content_type => /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
 
end

app/models/ontechnology.rb
class Ontechnology < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :ontechnology_img, :styles => { :medium => "500x300#", :small => "350x250>" }, :default_url => "missing.jpg"
	validates_attachment_content_type :ontechnology_img, :content_type => /\Aimage\/.*\Z/
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :image, :styles => { :medium => "500x300#", :small => "350x250>" }, :default_url => "missing.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user

	

	has_attached_file :product_img, :styles => { :medium => "500x300#", :small => "350x250>" }, :default_url => "missing.jpg"
	validates_attachment_content_type :product_img, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :products
	has_many :careers
	has_many :pictures
	has_many :ontechnologies

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
before_action :find_career, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
before_action :authenticate_user!, except: [:index, :show]

def index
	
		@careers = Career.all.order("created_at DESC")
end

def show
	#@comments = Comment.where(career_id: @career)
	#@random_career = career.where.not(id: @career).order("RANDOM()").first
end

def new
	@career = current_user.careers.build
end

def create
	@career = current_user.careers.build(career_params)

	if @career.save
		redirect_to @career
	else
		render 'new'
	end
end

def edit
end

def update
	if @career.update(career_params)
		redirect_to @career
	else
		render 'edit'
	end
end

def destroy
	@career.destroy
	redirect_to root_path
end

def upvote
	@career.upvote_by current_user
	redirect_to :back
end

def downvote
	@career.downvote_by current_user
	redirect_to :back
end

private

def find_career
	@career = Career.find(params[:id])
end

def career_params
	params.require(:career).permit(:advertiser, :title, :description, :qualification, :contract_nature, :salary, :start_date, :application_deadline, :career_img)
end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/dds_controller.rb
class DdsController < ApplicationController
    def home
    end

    def about_us
    	render
    end

    def csr
    	render
    end

    def business_continuity_management  
    	render
    end

    def cloud_computing
    	render
    end

    def project_management 
    	render
    end

    def partnerships
    	render
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :find_picture, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
before_action :authenticate_user!, except: [:index, :show]

def index
	
		@pictures = Picture.all.order("created_at DESC")
end

def show
	#@comments = Comment.where(picture_id: @picture)
	#@random_picture = picture.where.not(id: @picture).order("RANDOM()").first
end

def new
	@picture = current_user.pictures.build
end

def create
	@picture = current_user.pictures.build(picture_params)

	if @picture.save
		redirect_to @picture
	else
		render 'new'
	end
end

def edit
end

def update
	if @picture.update(picture_params)
		redirect_to @picture
	else
		render 'edit'
	end
end

def destroy
	@picture.destroy
	redirect_to root_path
end

def upvote
	@picture.upvote_by current_user
	redirect_to :back
end

def downvote
	@picture.downvote_by current_user
	redirect_to :back
end

private

def find_picture
	@picture = Picture.find(params[:id])
end

def picture_params
	params.require(:picture).permit(:advertiser, :title, :description, :qualification, :contract_nature, :salary, :start_date, :application_deadline, :picture_img)
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :find_product, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
before_action :authenticate_user!, except: [:index, :show]

def index
	
		@products = Product.all.order("created_at DESC")
end

def show
	#@comments = Comment.where(product_id: @product)
	#@random_product = product.where.not(id: @product).order("RANDOM()").first
end

def new
	@product = current_user.products.build
end

def create
	@product = current_user.products.build(product_params)

	if @product.save
		redirect_to @product
	else
		render 'new'
	end
end

def edit
end

def update
	if @product.update(product_params)
		redirect_to @product
	else
		render 'edit'
	end
end

def destroy
	@product.destroy
	redirect_to root_path
end

def upvote
	@product.upvote_by current_user
	redirect_to :back
end

def downvote
	@product.downvote_by current_user
	redirect_to :back
end

private

def find_product
	@product = Product.find(params[:id])
end

def product_params
	params.require(:product).permit(:title, :description, :url, :product_img)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dds_helper.rb
module DdsHelper
end

app/helpers/ontechnologies_helper.rb
module OntechnologiesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_denzbootstrapslider1.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/jquery-1.7.2.min.js"><\/script>')</script>


<script>
  $(document).ready(function(){
    $('.carousel').carousel({
      interval: 2000
    });
  });
</script>


<!--  Carousel - consult the Twitter Bootstrap docs at 
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide carousel-fade" data-ride="carousel"><!-- class of slide for animation -->
  <div class="carousel-inner">
    <div class="item active"><!-- class of active since it's the first item -->
      <%= link_to image_tag('tezhome4b.png', alt: "Edit Entry"), root_path, class: 'trybsresponsepics'  %>
      <div class="carousel-caption">
        <p>Logistics</p>
      </div>
    </div>
    <div class="item">
       <%= link_to image_tag('personaloutdoorbanner4.png', alt: "Edit Entry"), root_path, class: 'trybsresponsepics'  %>
      <div class="carousel-caption">
        <p>Personal</p>
      </div>
    </div>
    <div class="item">
       <%= link_to image_tag('corporatebanner4.png', alt: "Edit Entry"), root_path, class: 'trybsresponsepics'  %>
      <div class="carousel-caption">
        <p>Corporate</p>
      </div>
    </div>
    <div class="item">
      <!-- <img src="http://placehold.it/1200x480" alt="" />-->
       <%= link_to image_tag('householdbanner4.png', alt: "Edit Entry"), root_path, class: 'trybsresponsepics'  %>
      <div class="carousel-caption">
        <p>Household</p>
      </div>
    </div>
  </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

app/views/layouts/_denzbootstrapslider2.html.erb
<!DOCTYPE html>
<html>
<head>
    
            <style type="text/css">
            /*
                    inspired from http://codepen.io/Rowno/pen/Afykb 
                    */
                    .carousel-fade .carousel-inner .item {
                      opacity: 0;
                      transition-property: opacity;
                    }

                    .carousel-fade .carousel-inner .active {
                      opacity: 1;
                    }

                    .carousel-fade .carousel-inner .active.left,
                    .carousel-fade .carousel-inner .active.right {
                      left: 0;
                      opacity: 0;
                      z-index: 1;
                    }

                    .carousel-fade .carousel-inner .next.left,
                    .carousel-fade .carousel-inner .prev.right {
                      opacity: 1;
                    }

                    .carousel-fade .carousel-control {
                      z-index: 2;
                    }

                    /*
                    WHAT IS NEW IN 3.3: "Added transforms to improve carousel performance in modern browsers."
                    now override the 3.3 new styles for modern browsers & apply opacity
                    */
                    @media all and (transform-3d), (-webkit-transform-3d) {
                        .carousel-fade .carousel-inner > .item.next,
                        .carousel-fade .carousel-inner > .item.active.right {
                          opacity: 0;
                          -webkit-transform: translate3d(0, 0, 0);
                                  transform: translate3d(0, 0, 0);
                        }
                        .carousel-fade .carousel-inner > .item.prev,
                        .carousel-fade .carousel-inner > .item.active.left {
                          opacity: 0;
                          -webkit-transform: translate3d(0, 0, 0);
                                  transform: translate3d(0, 0, 0);
                        }
                        .carousel-fade .carousel-inner > .item.next.left,
                        .carousel-fade .carousel-inner > .item.prev.right,
                        .carousel-fade .carousel-inner > .item.active {
                          opacity: 1;
                          -webkit-transform: translate3d(0, 0, 0);
                                  transform: translate3d(0, 0, 0);
                        }
                    }

                     /*just for demo purpose */
                        html,
                        body,
                        .carousel,
                        .carousel-inner,
                        .carousel-inner .item {
                          height: 360px;
                        }

                        
                        .item:nth-child(1) {
                          background: #0c0f4a;
                        }

                        .item:nth-child(2) {
                          background: #0c0f4a;
                        }

                        .item:nth-child(3) {
                          background: #0c0f4a;
                        }
                        


            </style>

 <script type="text/javascript">
    $('#carouselHacked').carousel();
</script>

           

</head>
<body>

    <div id="carouselHacked" class="carousel slide carousel-fade" data-ride="carousel">

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
            <%= link_to image_tag('tezhome4b.png', alt: "home"), root_path, class: 'trybsresponsepics'  %>
                <div class="carousel-caption">
                <%= link_to "About us", about_us_path, class: "button" %>
                </div>
            </div>
            <div class="item">
            <%= link_to image_tag('personaloutdoorbanner4.png', alt: "Edit Entry"), root_path, class: 'trybsresponsepics'  %>
                <div class="carousel-caption">
                    <%= link_to "Cloud computing", cloud_computing_path, class: "button" %>
                    |
                    <%= link_to "Business continuity management", business_continuity_management_path, class: "button" %>
                </div>
            </div>
            <div class="item">
            <%= link_to image_tag('corporatebanner4.png', alt: "Edit Entry"), root_path, class: 'trybsresponsepics'  %>
                <div class="carousel-caption">
                    <%= link_to "Partnership", partnerships_path, class: "button" %>
                    <%= link_to "Project management", project_management_path, class: "button" %>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carouselHacked" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carouselHacked" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/layouts/_headernav2.html.haml
!!! 5
%html
%head

%body
	%nav.navbar.navbar-inverse
		.container
			.navbar-brand= link_to "Tez Logistics", root_path

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-left
					%li= link_to current_user.user_name, edit_user_registration_path
					%li= link_to "Sign out", destroy_user_session_path, method: :delete
			- else
				%ul.nav.navbar-nav.navbar-left
					= link_to "Sign in", new_user_session_path
					= link_to "Sign up", new_user_registration_path, class: "button"

app/views/layouts/_headernav4.html.erb
 <nav class="navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Double Dimensions", root_path, class: "navbar-brand" %>
      </div>
      <ul class="navbar-nav nav navbar-right">
        <% if user_signed_in? %>
          
        <% else %>
          
        <% end %>
      </ul>
      <% if user_signed_in? %>
        

      <% end %>
      <ul class="navbar-nav nav navbar-left">

          <li><%= link_to "About us", about_us_path %></li>



                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Our Services<span class="caret"></span></a>

                <ul class="dropdown-menu" role="menu">
                  
                    <li><%= link_to "Business continuity management", business_continuity_management_path %></li>
                    <li><%= link_to "Cloud computing", cloud_computing_path %></li>
                    <li><%= link_to "Project management", project_management_path %></li>
                    <li><%= link_to "Partnership", partnerships_path %></li>
                 
                </ul>
                </li>

          <li><%= link_to "Tech news", ontechnologies_path %></li>
          <li><%= link_to "CSR", csr_path %></li>
          <li><%= link_to "Careers", careers_path %></li>

      </ul>

      <ul class="navbar-nav nav navbar-right">

          <li><%= link_to "Email us" %></li>
          <li><%= link_to "Call us" %></li>

      </ul>

    </div>
  </nav>

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Double Dimensions
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

	= javascript_include_tag 'jquery-1.11.3.min.js', 'data-turbolinks-track' => true


	%link{:rel => "stylesheet", :href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css"}
	%link{:rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"}


	

%body

	= render 'layouts/headernav4'

	= render 'layouts/denzbootstrapslider2'
	


	%p.notice= notice
	%p.alert= alert

	.container
		.col-md-9
			= yield

		.col-md-3
			.row
				.fireplace2side
					= social_share_button_tag("doubledimensions")
					%h2 Contacts
					%br Norwich Union 7th Flr
					%br Phone: +254 726 275 304, +254 739 370 900
					%br P.O BOX 60463-00200 
					%br Nairobi, Kenya.
					%br ddimensionsit@gmail.com 


			.row
				.fireplace2side
					.trybsprofcircle10
						= link_to image_tag('brands1.png', alt: "Edit Entry"), root_path
					.trybsprofcircle10
						= link_to image_tag('brands2.png', alt: "Edit Entry"), root_path



	.footer1
		.col-md-4
			.divfold57
				%h2 Services
				%hr
				%br= link_to "About us", about_us_path
				%br= link_to "Our Services"
				%br= link_to "Tech news"
				%br= link_to "CSR", csr_path
				%br= link_to "Careers"

		.col-md-4
			.divfold57
				%h2 Partners
				%hr
				%li= link_to "Infohtech ict Consoutancy Agency", "http://www.infohtechict.com", target: :blank
		.col-md-4
			.divfold57
				%h2 Social media
				%hr
				.trybsprofcircle2
					= link_to image_tag('facebook.png', alt: "Edit Entry"), root_path
				%br
				.trybsprofcircle2
					= link_to image_tag('twitter.png', alt: "Edit Entry"), root_path
				%br
				.trybsprofcircle2
					= link_to image_tag('instagram.png', alt: "Edit Entry"), root_path
				%br
				.trybsprofcircle2
					= link_to image_tag('googleplus.png', alt: "Edit Entry"), root_path


	.footer
		.container
			%ul.nav.navbar-nav.navbar-right
				%li= link_to "copyright Double Dimensions © 2016 ", root_path
				%li= link_to "Partnered: Infohtech ict Consultancy Agency", "http://www.infohtechict.com", target: :blank